### ISSUE TITLE
Create Webapp "Ciclos Económicos"

### ISSUE THREAD

**Issue by Lennon0926** [ouslan/jp-webapp#9]
# Description 
Develop a web application named "Ciclos Económicos" that provides information and analysis on economic cycles. The application should be accessible at [jp.pr.gov/ciclos-economicos/](https://jp.pr.gov/ciclos-economicos/).

## Features
- Displaying graphical representations of economic cycles
- Providing detailed explanations of different economic phases
- Usage Instructions

**Comment by ouslan** [comment]
This has been implemented in main
